sudo: false
language: go
git:
  depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
  local_dir: public
  repo: liuzeaa/goblog
  fqdn:
  target_branch: master
  email: 1098367891@qq.com
  name: liuzeaa
