sudo: false
language: go
git:
  depth: 1
before_install: export GOPATH=$HOME/go
install: go get -v github.com/gohugoio/hugo
branches:
  only:
    - master # build master branch only
script: hugo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
